name: loan
version: 4.0.0-alpha.0
source: contracts
packages:
  - path: contracts/MapleLoan.sol
    contractName: MapleLoan
  - path: contracts/MapleLoanFactory.sol
    contractName: MapleLoanFactory
  - path: contracts/MapleLoanFeeManager.sol
    contractName: MapleLoanFeeManager
  - path: contracts/MapleLoanInitializer.sol
    contractName: MapleLoanInitializer
  - path: contracts/MapleLoanStorage.sol
    contractName: MapleLoanStorage
  - path: contracts/MapleLoanV4Migrator.sol
    contractName: MapleLoanV4Migrator
  - path: contracts/Refinancer.sol
    contractName: Refinancer
customDescription: Maple Loan Artifacts and ABIs
